PROMPT Creating Game Tables ...

CREATE TABLE GAME_TABLES (
    ID              VARCHAR(32) NOT NULL,
    NAME            VARCHAR(40) NOT NULL,
    DESCRIPTION     VARCHAR(50) ,
    MAX_CAPACITY    INT         NOT NULL,
    FROZEN          INT         NOT NULL,
    ACTIVE          INT         NOT NULL,
    STATUS          INT         NOT NULL,
    TYPE            INT         NOT NULL,
    CREATE_DATE     DATE        NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE PLAYERS (
    ID          VARCHAR(32) NOT NULL,
    NAME        VARCHAR(40) NOT NULL,
    PASSWORD    VARCHAR(16) NOT NULL,
    EMAIL       VARCHAR(50) NOT NULL,
    CONTACT     VARCHAR(15) NOT NULL,
    ADDRESS     VARCHAR(60) ,
    CREATE_DATE DATE        NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FLASH_GAMES (
    ID              VARCHAR(32) NOT NULL,
    DESCRIPTION     VARCHAR(40) NOT NULL,
    TABLE_ID        VARCHAR(32) NOT NULL,
    PLAYER_COUNT    INT         NOT NULL,
    START_TIME      DATE        NOT NULL,
    STATUS          INT         NOT NULL,
    END_TIME        DATE,
    PRIMARY KEY (ID)
);

CREATE TABLE GAME_DECKS (
    GAME_ID         VARCHAR(32) NOT NULL,
    PLAYER_ID       VARCHAR(32) NOT NULL,
    SUIT            VARCHAR(7)  NOT NULL,
    RANK            VARCHAR(5)  NOT NULL
);

CREATE TABLE GAME_BIDS (
    GAME_ID     VARCHAR(32) NOT NULL,
    PLAYER_ID   VARCHAR(32) NOT NULL,
    BID_ORDER   INT         NOT NULL,
    BID_VALUE   INT         NOT NULL,
    BID_TIME    DATE        NOT NULL,
    STATUS      INT         NOT NULL
);

CREATE INDEX GAME_DECKS_IK ON GAME_DECKS (GAME_ID);

CREATE INDEX GAME_BIDS_IK ON GAME_BIDS (GAME_ID);